spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/llavero_seguro}
    username: ${DB_USERNAME:llavero_dev}
    password: ${DB_PASSWORD:llavero_dev_password}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
